### ISSUE TITLE
F12(find in valadoc) dont works for me

### ISSUE THREAD

**Issue by gavr123456789** [wolfgangmauer/valaDevelop#10]
Dude, I just launched your valaDevelop for the first time, it's realy cool!
When I press F12 with the selected text, the selection disappears but nothing happens. In the console, I get the next bunch of asserts(all this occurs after one press F12 ).
VM with ubuntu 18.04 LTS, valadoc package installed.
https://pastebin.com/VN3vAnHU

**Comment by wolfgangmauer** [comment]
Are you shore the other dependencies are installed?!
I will analyse on VM...

**Comment by wolfgangmauer** [comment]
Sorry, wrong version...
For all features/performance to work, you need libvala-0.46 (https://gitlab.gnome.org/GNOME/vala/tree/wip/fast-vapi)

**Comment by wolfgangmauer** [comment]
Static linked libvala now should work on any system...
