### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by gavr123456789** [wolfgangmauer/valaDevelop#12]
Add gtksourceview-3.0 theme selection

[Council ]
Do View from a popover menu 1 ToogleButtons.
The current one is not obvious, for example I can't close it if I don't move the mouse to one of the selection points.

![rar](https://user-images.githubusercontent.com/30507409/55298842-a1be0f00-5438-11e9-9a9f-99243d6867e6.gif)

**Comment by wolfgangmauer** [comment]
A lot of settings missing by now, next on list

**Comment by wolfgangmauer** [comment]
> The current one is not obvious, for example I can't close it if I don't move the mouse to one of the selection points.

This looks like a GTK-Bug?! If you use Fullscreen i think it works like expected?!

**Comment by wolfgangmauer** [comment]
Options added, [Council ] fixed
