### ISSUE TITLE
Adoption: Vala cannot be statically linked with the current license

### ISSUE THREAD

**Issue by itisrazza** [wolfgangmauer/valaDevelop#14]
I was looking to add `libvala` and `gee` as statically linked components (as per @wolfgangmauer's comment on [my pull request](https://github.com/wolfgangmauer/valaDevelop/pull/13#issuecomment-480218754)).

However, LGPL must be dynamically linked for the code to keep its license. Statically linked applications must adopt LGPL or allow the user to relink it. (I have no idea how to do that.)

This is also something that's advertised in the [Readme](https://github.com/wolfgangmauer/valaDevelop/blob/master/README.md):
> Now valaDevelop comes with static linked libvala-0.46, so it should be run on any system with installed valac >= 0.40

I'm working on getting the libgee and libvala to work, but I thought to let people know of possible legal issues.

Here's some more info:
* https://stackoverflow.com/a/10179181
* https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic

**Comment by wolfgangmauer** [comment]
Please read the info by yourself!
> However, LGPL must be dynamically linked for the code to keep its license.

That's wrong!
(1) If you statically link against an LGPLed library, **you must also provide your application in an object (not necessarily source) format**

> I'm working on getting the libgee and libvala to work

That's fine.
> but I thought to let people know of possible legal issues.

Please do not worry the users unnecessarily.

**Comment by wolfgangmauer** [comment]
If you want to build libvala-0.46 and link it static, you have to use the "--enable-static" option.

**Comment by wolfgangmauer** [comment]
This is the [Makefile.txt](https://github.com/wolfgangmauer/valaDevelop/files/3050344/Makefile.txt) i use to build the valaDevelop binary
