### ISSUE TITLE
Vala sources 

### ISSUE THREAD

**Issue by Janluke0** [wolfgangmauer/valaDevelop#16]
I'm getting interested to vala,
So can you release the vala sources file instead of the c ones?

Thank you

Ps
I read the issue #1 but since you abandoned the development, you could allow somebody else to work on it

**Comment by gavr123456789** [comment]
@Janluke0 also, u need to check this https://mail.gnome.org/archives/vala-list/2019-May/thread.html
VS Code is great for development on Vala, I recently recorded a [demo](https://youtu.be/3yyDdA5IMLI) of working with gdb. 
Several Language Servers are also being developed [here](https://github.com/benwaffle/vala-language-server) and [here](https://gitlab.gnome.org/esodan/gvls).

Here some its examples of autoomplition https://imgur.com/a/G2fLT4K https://imgur.com/a/LWByJac

Same for builder  
![image](https://user-images.githubusercontent.com/30507409/66058369-f014ad80-e542-11e9-8dd6-1b1828a78d58.png)

**Comment by wolfgangmauer** [comment]
Other opensource IDE's around...

**Comment by Janluke0** [comment]
@gavr123456789 fisrt of all thank you for your exhaustive answer.

The interest about this ide was more because it could be a good way to study vala and its internals with a "well working" application than to just use it.

i'm currently using vscode with vala-code.
I saw that it have a language server support so i tried to build it with  both of them [here](https://github.com/Janluke0/vala-code/).

Waring, errors and symbol definition resolution works well with both.
But apparently they don't support code completion, do you know what gnome builder use(maybe talking somewhere else)?

@wolfgangmauer  i know but you did a good work and i got interested, but i have a little suggestion:
you could start a crowfounding to release the source, i'll contribuite anyway

**Comment by gavr123456789** [comment]
@thegreatrazz 
Screenshots of the code completion was taken from [this](https://gitter.im/vala-language-server/community#) conference where VLS's maintainer sitting. Be free to go there and ask things.  

And [here](https://github.com/Valama/valama) is an IDE just like this one, but alll code opened on Vala.   

GNOME Builder using their own LS. [Issue1](https://gitlab.gnome.org/GNOME/gnome-builder/issues/375) [Issue2](https://gitlab.gnome.org/GNOME/gnome-builder/issues/1000).  The developers themselves do not understand Vala, and argue that any improvements related to Vala should come from the developers of Vala, and now they are very few.  
  
>because it could be a good way to study vala  

By the way, in case you haven't noticed, [there](https://wiki.gnome.org/Projects/Vala/Documentation#Tutorials) are a tons of guides and code examples in all areas. (those which "(Russian)" added I ^^ )  

PS Can u [add](https://github.com/benwaffle/vala-language-server/issues/37) what u did step by step to make vls on vs code works. I still dont understand how to make vls run immediately, without compiling a project that gives a new instance of vs code with a working vls.

**Comment by Janluke0** [comment]
@gavr123456789 
about your PS: actualy i used it only in that way.  i used to think that put it on work was more simple.
i will open a issue to ask to the dev  to merge the vls branch into the master

**Comment by gavr123456789** [comment]
@Janluke0 Pssss https://github.com/philippejer/vala-language-server-alpha
