### ISSUE TITLE
Cant open valaDevelop

### ISSUE THREAD

**Issue by gavr123456789** [wolfgangmauer/valaDevelop#6]
```
$ '/home/gavr/valaDevelop-master/valaDevelop' 
/home/gavr/valaDevelop-master/valaDevelop: error while loading shared libraries: libvala-0.40.so.0: cannot open shared object file: No such file or directory
```
Im on Fedora 29 with 0.42.5 valac version. I'm guessing that the binary is tightly tied to the version 0.40 and not >=0.40.

P.S. 
It's so cool that someone finally decided to solve the problem of not having a normal IDE for Vala. Now most of all there is no working VLS.

**Comment by wolfgangmauer** [comment]
Thanks ;-) Just for now, link the "libvala-0.40.so.0" to the one you have...

**Comment by wolfgangmauer** [comment]
Until there is an installation, the "ln" must suffice.
I ask the vala-list to help to make a installation, but none can/want to help.,,

**Comment by gavr123456789** [comment]
I found your project just from the Vala-list mailing list. I'm new to Vala and Linux myself so can't help. I used to work with Qt, and recently discovered Vala + Gtk, and I'm just excited about them!

**Comment by gavr123456789** [comment]
may be package in Appimage or Flatpak, still dont works with 0.44.

**Comment by wolfgangmauer** [comment]
I'm sorry for that, but the only way is to install libvala-0.42
There are some "breaking changes" between 0.42 and 0.44 so you have to use 0.42
I think is is possible to install side by side

**Comment by wolfgangmauer** [comment]
Publish source code

**Comment by gavr123456789** [comment]
A very clever solution to open the code without opening the code, which is only possible in Vala XDDD

**Comment by wolfgangmauer** [comment]
Static linked libvala now should work on any system...
