### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by gavr123456789** [wolfgangmauer/valaDevelop#7]
It would be cool to have a Windows version. Now the only way to develop there is MSYS2 and VS Code / Sublime which only have syntax highlighting.

**Comment by wolfgangmauer** [comment]
I think, even if i make a windows version, you need msys (Gtk/Vala) because it's GNOME based ?!

**Comment by gavr123456789** [comment]
There are 2 answers:
https://stackoverflow.com/questions/49092784/how-to-distribute-a-gtk-application-on-windows
https://stackoverflow.com/questions/55037063/how-to-pack-a-vala-application-under-windows?noredirect=1#comment96832678_55037063

**Comment by wolfgangmauer** [comment]
Ok, will look at it...

**Comment by wolfgangmauer** [comment]
Since "spawn_async" on windows not working correct, is it not possible to build a windows version :-(
